Bissmark/SEIR64-homework

04-Dineth-Rajapakse/wk01/2-tue/Part1/index.html, 04-Dineth-Rajapakse/wk01/2-tue/Part1/js/exercises.js
- How difficult did you find this (out of 10)? (0 being no problems at all, 10 being impossible) 8/10
- Was there anything that you struggled with? - i struggled with variables and functions, but went over it again yesterday night. Struggled with Part 2 of the calculator (return)
- Is there any particular code you want me to look into? help with Part 2 please
- Is there anything that you'd like some further information on? return functions
- Roughly how long did it take? 3-4 hrs
=> Tuesday Homework - Calculator

01-Adam-Shuvalov/wk02/2-tue/calculator.html, 01-Adam-Shuvalov/wk02/2-tue/calculator.js, 01-Adam-Shuvalov/wk02/2-tue/strings.html, 01-Adam-Shuvalov/wk02/2-tue/strings.js
- How difficult did you find this 5/10
- Was there anything that you struggled with? I struggled figuring out how 'return' works. I figured out after some research that it stops function after being called
- N/A
- I'd like to learn more about how 'return' works in terms of passing an output to subsequent functions.
- Roughly how long did it take? 1.5 hours
=> Tues homework (1/2 of strings completed)

08-Frankie-Yang/wk01/2-tue/calculator/Calculator.html, 08-Frankie-Yang/wk01/2-tue/calculator/Calculator.js
- How difficult did you find this (out of 10)? (0 being no problems at all, 10 being impossible) 
i found part 1 and part 2 is relatively easy. for string part, it requires further study and investigation
not for part 1 and 2.
i have tried different ways for part 1 and part 2.
sometimes the coding could be too long in terms of length. anyway we could improve that ?
45 minutes to finish part 1 and part 2.
=> Calculator Part 1 and Part 2

05-Dominic-Wong/wk01/2-tue/calculator/index.html, 05-Dominic-Wong/wk01/2-tue/calculator/js/calculator.js, 05-Dominic-Wong/wk01/2-tue/strings/index.html, 05-Dominic-Wong/wk01/2-tue/strings/js/stringHw.js
- How difficult did you find this (out of 10)? (0 being no problems at all, 10 being impossible) 5 
- Was there anything that you struggled with? string manipulation methods.
- Is there anything that you'd like some further information on? Advice on more efficient code. 
- Roughly how long did it take? <3hours and 3 negronis.
=> caculator & strings homework 21 March

07-Howard-Wang/wk01/2-tue/Calculator/index.html, 07-Howard-Wang/wk01/2-tue/Calculator/js/calculate.js, 07-Howard-Wang/wk01/2-tue/String/index.html, 07-Howard-Wang/wk01/2-tue/String/js/string.js
- How difficult did you find this (out of 10)?  5/10
- Was there anything that you struggled with? struggled with two parts therefore left blank
- Roughly how long did it take? for the parts completed, took roughly 1-1.5hrs
=> Homework for 21st MARCH

17-Riley-Mercer/wk01/2-tue/calculator/index.html, 17-Riley-Mercer/wk01/2-tue/calculator/js/calculator.js, 17-Riley-Mercer/wk01/2-tue/strings/index.html, 17-Riley-Mercer/wk01/2-tue/strings/js/strings.js
3? Some small issues, but mostly with using incorrect words that I found on MDN
Verbing function took me the longest
Not particularly!
No thank you
~2hrs
=> Week 1, Tuesday - Homework Completed Full

13-Karen-Liang/wk01/2-tue/calculator/index.html, 13-Karen-Liang/wk01/2-tue/calculator/js/calculator.js, 13-Karen-Liang/wk01/2-tue/strings/index.html, 13-Karen-Liang/wk01/2-tue/strings/js/strings.js
COMPLETE_If you had no problems you can just leave it empty_
- calculator - 0.  Strings - 8
- In strings I used slice and substring, that was a bit confusing to understand, I got the answer but also do not completely understand the topic.
- Strings -> Q2 mixUp
- slice and substring is needed :)
- calculator - 1hr. Strings - 2.5hr, q1 was easy, q2 took the longest.
=> wk01 hw calculator and strings

14-Kee-Ming-Brandon/wk01/2-tue/calculator/index.html, 14-Kee-Ming-Brandon/wk01/2-tue/calculator/js/exercises.js, 14-Kee-Ming-Brandon/wk01/2-tue/strings/index.html, 14-Kee-Ming-Brandon/wk01/2-tue/strings/js/exercises.js
10
-
-
Part 2: what percentage that area is of the squared result (#3).
I am confuse with this. squared result is #2. 
With my understand the "area is (xx%) of the squared result , I use area/squared which give me >100%.
2-3 casually
=> COMPLETE wk01 2-tue Homework

02-Akiko-Yamasaki/wk01/2-tue/calculator/index.html, 02-Akiko-Yamasaki/wk01/2-tue/calculator/main.js, 02-Akiko-Yamasaki/wk01/2-tue/strings/index.html, 02-Akiko-Yamasaki/wk01/2-tue/strings/main.js
=> Calculation function

12-Joshua-Ling/wk01/2-tue/index.html, 12-Joshua-Ling/wk01/2-tue/javascript/javascript.js
- 2
- Using string functions.
- my last one, only if you want to.
- 1-2 hours
=> Added week 1 Tuesday Calculator Homework

14-Kee-Ming-Brandon/wk01/2-tue/strings/js/exercises.js
=> RESUBMIT wk01 2-tue Homework

16-Ramez-Al-Siddiq/wk01/2-tue/calculator/calculator.js, 16-Ramez-Al-Siddiq/wk01/2-tue/calculator/index.html, 16-Ramez-Al-Siddiq/wk01/2-tue/strings/index.html, 16-Ramez-Al-Siddiq/wk01/2-tue/strings/strings.js
- How difficult did you find this (out of 10)? (0 being no problems at all, 10 being impossible) 
- I think it was a solid 7 - some exercises were doable, but others I really struggled with.
- I think the mixUp exercise was quite difficult.
- the mixUp exercise so that I understand what I should have done.
- Understanding the difference between console.log and return.
- I spent 3 hours on the exercises, but I was unable to complete.
=> Calculator and Strings Exercises 21/03

18-Roxanne-Liu/wk01/2-tue/calculator/index.html, 18-Roxanne-Liu/wk01/2-tue/calculator/js/answer.js, 18-Roxanne-Liu/wk01/2-tue/strings/index.html, 18-Roxanne-Liu/wk01/2-tue/strings/js/answer.js
INCOMPLETE
6
- Yeah, that FixStart exercise in strings.
- - Yeah, that FixStart exercise in strings.
- For loop pls
- 2 hoursish
=> Week1_Tuesday_21_Mar_2023_Homework

06-Eugene-Teo/wk01/2-tue/index_210323.html, 06-Eugene-Teo/wk01/2-tue/js_homework_calculator_210323.js
COMPLETE
String task - INCOMPLETE (not included)
8
Understanding the questions, what were the questions asking for. It's slowly getting better, but often I'm still stuck at the beginning, thinking of what and how to "start" typing answers. Especially bad for Part 2 Q4, took way too long to comprehend that one line of question re square and area2. Also spent significant time trying to debug when my results don't show up in console.
Actually just struggling with JS in general, to be honest. The JS pre-work was a massive slog 
- Is there …
=> EUGENE_CALCULATOR_TASK_JS

19-Sambid-Rana/wk01/2-tue/calculator/.vscode/settings.json, 19-Sambid-Rana/wk01/2-tue/calculator/index.html, 19-Sambid-Rana/wk01/2-tue/calculator/script.js, 19-Sambid-Rana/wk01/2-tue/strings/index.html, 19-Sambid-Rana/wk01/2-tue/strings/script.js
7
Yes, string methods.
Yes, from /strings/script.js. Couldn't get the correct output.
More info on functions.
4-5hrs
=> 22nd March- Calculator and Strings

22-Victor-Worobec/wk01/2-tue/Strings/exercises.js, 22-Victor-Worobec/wk01/2-tue/Strings/index.html, 22-Victor-Worobec/wk01/2-tue/The_Calculator/exercises.js, 22-Victor-Worobec/wk01/2-tue/The_Calculator/index.html
- 6
- Find out the different available function that are built in.
- Nope.
- Nope.
- About 5 hrs whilst doing errands in between.
=> Submitted day 2's homework (strings and calculator excercise)

20-Stuart-Cannone/wk01/2-tue/index.html, 20-Stuart-Cannone/wk01/2-tue/js/homework.js
- 7/10
- The later sections of the homework that needed more complex if statements
- 2 hours
=> Calculator Attempt

01-Adam-Shuvalov/wk02/3-wed/wednesdayhw/arrayandfunctions/arrayandfunctions.js, 01-Adam-Shuvalov/wk02/3-wed/wednesdayhw/index.html
- How difficult did you find this (out of 10)? 4/10
- Was there anything that you struggled with? N/A
- Is there any particular code you want me to look into? N/A
- Is there anything that you'd like some further information on? N/A
- Roughly how long did it take? 2.5 hours
=> Wednesday Homework - Completed except for hangman

17-Riley-Mercer/wk01/3-wed/Arrays & Functions/index.html, 17-Riley-Mercer/wk01/3-wed/Arrays & Functions/js/working.js, 17-Riley-Mercer/wk01/3-wed/Wordgame/Wordgame - Hangman/index.html, 17-Riley-Mercer/wk01/3-wed/Wordgame/Wordgame - Hangman/js/working.js, 17-Riley-Mercer/wk01/3-wed/Wordgame/Wordgame - Wheel/index.html, 17-Riley-Mercer/wk01/3-wed/Wordgame/Wordgame - Wheel/js/working.js, 17-Riley-Mercer/wk01/3-wed/Wordgame/index.html, 17-Riley-Mercer/wk01/3-wed/Wordgame/js/working.js
6
I could not work out how to make the hangman code not record duplicate guesses
Three hours
=> Complete Homework (very almost) - Weds 22/03/2023

04-Dineth-Rajapakse/wk01/3-wed/index.html, 04-Dineth-Rajapakse/wk01/3-wed/js/exercises.js
- How difficult did you find this (out of 10)?  8/10 (0 being no problems at all, 10 being impossible)
- Was there anything that you struggled with? last question and vowel question
- Is there any particular code you want me to look into? my last two questions
- Is there anything that you'd like some further information on? i googled to find the answer (sorry if thats cheating but im being honest :) ) so i would like to review the answer to ensure i understand
- Roughly how long did it take? 2-3 hrs
=> INCOMPLETE

05-Dominic-Wong/wk01/3-wed/Array & Functions/index.html, 05-Dominic-Wong/wk01/3-wed/Array & Functions/js/homework.js, 05-Dominic-Wong/wk01/3-wed/Word Guesser/index.html, 05-Dominic-Wong/wk01/3-wed/Word Guesser/js/homework.js
- How difficult did you find this (out of 10)? (0 being no problems at all, 10 being impossible) 6
- Was there anything that you struggled with? Adding in the max # of guesses part to the hangman code.
- Roughly how long did it take? 3-4hrs
=> COMPLETED 22 Mar Homework

08-Frankie-Yang/wk01/3-wed/ArrayFunction.html, 08-Frankie-Yang/wk01/3-wed/ArrayFunction.js
- 7
- new functions in JS everyday to  resolve the problems
- some people use return function , some people const a new variable.
- can be confusing
- some people can do all exercises , some like me can only do a few. a bit concerned.
- about 2 hours
=> day 02 - Array Practice

15-Maggie-Cameron/wk01/2-tue/string/exercises.js, 15-Maggie-Cameron/wk01/2-tue/string/index.html, 15-Maggie-Cameron/wk01/3-wed/array/index.html, 15-Maggie-Cameron/wk01/3-wed/array/js/exercises.js
- 8
time management. I spent the majority of the time trying to create a new file in terminal then have the console log show an input from 'code' - it kept saying something like 'location cannot be found' or 'file does not exist'. I have no idea what I did to eventually get it working. From there I found the task manageable although I had run out of time at that stage. Today I have just been copying existing working folders to get around the terminal issue. Looking forward to giving tonight's homework a proper crack.  
- Is there any particular code you want me to look into? 
- Is there anything …
=> calculator homework

09-James-Holton/wk01/2-tue/calculator/index.html, 09-James-Holton/wk01/2-tue/calculator/js/Calculator.js, 09-James-Holton/wk01/2-tue/strings/index.html, 09-James-Holton/wk01/2-tue/strings/js/Strings.js, 09-James-Holton/wk01/3-wed/Array/index.html, 09-James-Holton/wk01/3-wed/Array/js/ArraryFunctions.js, 09-James-Holton/wk01/3-wed/Hangman/index.html, 09-James-Holton/wk01/3-wed/Hangman/js/hangman.js
If you had no problems you can just leave it empty
How difficult did you find this (out of 10)? (0 being no problems at all, 10 being impossible)
5
Was there anything that you struggled with?
getting the notBad function to work properly definitely took me the longest to figure out.
Is there any particular code you want me to look into?
It definitely needs some cleaning up and better names of objects but in general if you could point out any code I could've shortened or formatted better that would be great.
Is there anything that you'd like some further information on?
Roughly how long did it take?
3 hours give or take including research and code.
=> Parts 1 and 2 calculator task & strings tasks

09-James-Holton/wk01/2-tue/strings/js/Strings.js
Changes made to original code to provide correct results
=> Strings edited

12-Joshua-Ling/wk01/3-wed/index.html, 12-Joshua-Ling/wk01/3-wed/js/javascript.js
=> Wed Homework Arrays

14-Kee-Ming-Brandon/wk01/3-wed/array-and-function/index.html, 14-Kee-Ming-Brandon/wk01/3-wed/array-and-function/js/solutions.js, 14-Kee-Ming-Brandon/wk01/3-wed/word-guesser/index.html, 14-Kee-Ming-Brandon/wk01/3-wed/word-guesser/js/solutions.js
=> COMPLETE wk01 3-wed Homework: Arrays, Function and Word Guess

20-Stuart-Cannone/wk01/3-wed/index.html, 20-Stuart-Cannone/wk01/3-wed/js/3wedhomework.js
- 6/10
- the last question finding the longest word in an array
- 2 hours
=> Day 3 Homework tasks

02-Akiko-Yamasaki/wk01/3-wed/Array/index.html, 02-Akiko-Yamasaki/wk01/3-wed/Array/js/main.js
7
with various methods
- 3 hours
=> Array and loop function HW

16-Ramez-Al-Siddiq/wk01/3-wed/array-and-functions.js, 16-Ramez-Al-Siddiq/wk01/3-wed/index.html
- How difficult did you find this (out of 10)? (0 being no problems at all, 10 being impossible) - 6
- Was there anything that you struggled with? - the bonus exercises (I did not know where to start.
- Roughly how long did it take? 2 hours
=> Complete (almost fully apart from some bonus exercises) - Wed 23/03/2023

22-Victor-Worobec/wk01/3-wed/Arrays/index.html, 22-Victor-Worobec/wk01/3-wed/Arrays/js/exercises.js
- 6
- Some of code worked as unexpected. (see line 221 onwards)
- 
- why does my else conditional on line 202 never get executed? Might be simple but I'm really tired today 
- 
- Just above. Happy to hop in a breakout room real quick to have it explained.
-
- about 4hrs active work
=> Uploaded day 3's homework. 90% complete (total)

21-Tristan-Bartolome/wk01/3-wed/arrays/exercises.js, 21-Tristan-Bartolome/wk01/3-wed/arrays/index.html
*INCOMPLETE*
- 6
- I struggled with part 4 (sumArray/multiplyArray)  setting up the loop. Also struggled with reverseString
- Just my loops
- Just a bit of a breakdown about loops (still a bit confusing)
- 5-6 hours
=> Arrays Homework

19-Sambid-Rana/wk01/3-wed/array-and-functions/.vscode/settings.json, 19-Sambid-Rana/wk01/3-wed/array-and-functions/index.html, 19-Sambid-Rana/wk01/3-wed/array-and-functions/js/script.js, 19-Sambid-Rana/wk01/3-wed/the-word-guesser/index.html, 19-Sambid-Rana/wk01/3-wed/the-word-guesser/js/script.js
7
nested if else statement in loops
Yes please, the word guess - couldn't do the bonus section 
Nested loops and if-else statements
-  6-7, got stuck on Word guess.
=> March 22nd HW - Array, function and Word Guesser

06-Eugene-Teo/wk01/3-wed/arraysnfunctions_Eugene_220323.js, 06-Eugene-Teo/wk01/3-wed/index.html
7-8/10
Having to come up with loops for more complicated questions 
- Is there any particular code you want me to look into? 
Q5 and Q7(not finished, unsure)
Q7 walkthrough step by step
Too long as usual. 3-4hours? Includes constant checking and fixing of code
=> INCOMPLETE_Q7_220323_ARRAYS_FUNCTIONS_EUGENE

10-Jordan-Borg/wk01/2-tue/Calculator.html, 10-Jordan-Borg/wk01/2-tue/Calculator.js, 10-Jordan-Borg/wk01/2-tue/Strings.html, 10-Jordan-Borg/wk01/2-tue/Strings.js, 10-Jordan-Borg/wk01/3-wed/arrays.js, 10-Jordan-Borg/wk01/3-wed/index.html, 10-Jordan-Borg/wk01/3-wed/word.js, 10-Jordan-Borg/wk01/4-thu/Geometry/Rectangle.js, 10-Jordan-Borg/wk01/4-thu/Geometry/Triangle.js, 10-Jordan-Borg/wk01/4-thu/Geometry/index.html
8/10 giving my braincells a big crack. 
submitting homework, and essentially all areas of Java at the moment but I am feeling more positive each day.
- Is there any particular code you want me to look into? 
all
all
10hrs
=> Tuesday, Wednesday & Thursday homework

07-Howard-Wang/wk01/3-wed/loopandarray/index.html, 07-Howard-Wang/wk01/3-wed/loopandarray/js/loopandarray.js
- How difficult did you find this (out of 10)?  6/10
- Roughly how long did it take? 2.5-3 hrs
=> Complete Homework for 22nd MARCH

01-Adam-Shuvalov/wk01/3-wed/wednesdayhw/arrayandfunctions/arrayandfunctions.js, 01-Adam-Shuvalov/wk01/3-wed/wednesdayhw/index.html
=> Reupload of Wednesday night's HW

11-Joshua-Spicer/wk01/3-wed/index.html, 11-Joshua-Spicer/wk01/3-wed/index.js
Took me about 2 hours including research time. Wasn't able to get to everything but will revise on the weekend.
=> Better_Than_Your_Message_Goes_Here

08-Frankie-Yang/wk01/4-thu/index.html, 08-Frankie-Yang/wk01/4-thu/js/java.js
- 10
- the double bonus of Credit card
- credit card
- double bonous part
- 2 hours
=> w01 - Thu - homework

01-Adam-Shuvalov/wk01/4-thu/homework/homework.js, 01-Adam-Shuvalov/wk01/4-thu/homework/index.html
- How difficult did you find this (out of 10)? 
6-7/10
- Is there any particular code you want me to look into? 
I'd like some advice on the 2 parts of bank I didnt complete
- Is there anything that you'd like some further information on? 
I'd like a bit more information on accessing objects within arrays
- Roughly how long did it take? 
3 hours
=> Thursday Night HW Complete

05-Dominic-Wong/wk01/4-thu/cash register/index.html, 05-Dominic-Wong/wk01/4-thu/cash register/js/exercises.js, 05-Dominic-Wong/wk01/4-thu/credit card validation/index.html, 05-Dominic-Wong/wk01/4-thu/credit card validation/js/exercises.js, 05-Dominic-Wong/wk01/4-thu/geometry/index.html, 05-Dominic-Wong/wk01/4-thu/geometry/js/exercises.js
- How difficult did you find this (out of 10)? (0 being no problems at all, 10 being impossible) 8
- Was there anything that you struggled with? credit card validator was challenging
- Is there anything that you'd like some further information on? Advise if there are areas where code can be more dry 
- Roughly how long did it take? 5 - 6 hours
=> COMPLETED HW 23 March 

12-Joshua-Ling/wk01/4-thu/index.html, 12-Joshua-Ling/wk01/4-thu/js/javascript.js
- 3
- I tried using arrow functions to make methods for the bank object but it couldn't handle arrays.
- I didn't know how to find out if a triangle is obtuse or not.
- 3 hours
=> Thurs Homework Objects

02-Akiko-Yamasaki/wk01/4-thu/objects/index.html, 02-Akiko-Yamasaki/wk01/4-thu/objects/js/main.js
it is not complete, it is rather a disaster.
- 9
- converting string to number/ getting the machine to find number out of strings. i could not follow the formula i found online to figure out how to get facts about triangles. have trouble with where to use "return" in code block
- last few are not complete but i started thinking what should be done in English
- 5 hours, but mostly researching on how to write things
=> Object homework

18-Roxanne-Liu/wk01/2-tue/strings/js/answer.js, 18-Roxanne-Liu/wk01/3-wed/arrayAndFunctions/index.html, 18-Roxanne-Liu/wk01/3-wed/arrayAndFunctions/js/answer.js, 18-Roxanne-Liu/wk01/3-wed/theWordGuesser/index.html, 18-Roxanne-Liu/wk01/3-wed/theWordGuesser/js/answer.js, 18-Roxanne-Liu/wk01/4-thu/GeometryFunctionLab/index.html, 18-Roxanne-Liu/wk01/4-thu/GeometryFunctionLab/js/answer.js, 18-Roxanne-Liu/wk01/4-thu/TheCashRegister/index.html, 18-Roxanne-Liu/wk01/4-thu/TheCashRegister/js/answer.js
- 7
- Yeah the Wheel of Fortune and Hangman
- 3 hours
=> w1_Wed_22_Mar_2023

10-Jordan-Borg/wk01/4-thu/Geometry/Rectangle.js, 10-Jordan-Borg/wk01/4-thu/Geometry/Triangle.js, 10-Jordan-Borg/wk01/4-thu/cashRegister/The Cash Register.js, 10-Jordan-Borg/wk01/4-thu/cashRegister/index.html
8/10 wasn't able to get through all the work. 
all to be honest, but feeling a tiny bit more clear today
Not sure yet, just a refresh on everything
all ^
1.5hrs till I gave up
=> Thursday homework

04-Dineth-Rajapakse/wk01/4-thu/index.html, 04-Dineth-Rajapakse/wk01/4-thu/js/Part1&2.js, 04-Dineth-Rajapakse/wk01/4-thu/js/TheCashRegister.js
lost the blurb!
part 1 and 2 were straight forward
cash register 7/10 - i need to spend some time refreshing arrays in functions and i will try complete again
=> Part1,2 + cash register

11-Joshua-Spicer/wk01/4-thu/index4.html, 11-Joshua-Spicer/wk01/4-thu/index4.js, 11-Joshua-Spicer/wk01/4-thu/index4b.js, 11-Joshua-Spicer/wk01/4-thu/index4c.js
2.6 hours including research. No more questions at the moment.
=> Thursday_HW

22-Victor-Worobec/wk01/4-thu/geometry-function-lab/index.html, 22-Victor-Worobec/wk01/4-thu/geometry-function-lab/js/exercises.js
4
Line 328 (setting a key:pairs value to a variable existing outside scope of object to be returned but inside scope of function it is contained in - is this bad?)
4hrs active coding
=> Day 4 Homework - Completed (except final bonus)

20-Stuart-Cannone/wk01/4-thu/index.html, 20-Stuart-Cannone/wk01/4-thu/js/day4homework.js
Complete to Geometry 
- 6
- keeping up with my meesy code 
- 1.5 hours
=> Day 4 Geometry

09-James-Holton/wk01/4-thu/cashregister/index.html, 09-James-Holton/wk01/4-thu/cashregister/js/cashregister.js, 09-James-Holton/wk01/4-thu/creditcard/index.html, 09-James-Holton/wk01/4-thu/creditcard/js/creditcard.js, 09-James-Holton/wk01/4-thu/geometryfunction/index.html, 09-James-Holton/wk01/4-thu/geometryfunction/js/geometryfunction.js, 09-James-Holton/wk01/4-thu/javabank/index.html, 09-James-Holton/wk01/4-thu/javabank/js/javabank.js
the first 2 tasks were 4/10.
the credit card was more difficult: 5.
the bank was difficult and not completed: 8
the javabank and how to approach it
how the "this." function works in the code CJ provided.
3-4 hour
=> Thursday's homework

19-Sambid-Rana/wk01/4-thu/credit-card-validation/.vscode/settings.json, 19-Sambid-Rana/wk01/4-thu/credit-card-validation/index.html, 19-Sambid-Rana/wk01/4-thu/credit-card-validation/js/script.js, 19-Sambid-Rana/wk01/4-thu/geometry-function-lab/.vscode/settings.json, 19-Sambid-Rana/wk01/4-thu/geometry-function-lab/index.html, 19-Sambid-Rana/wk01/4-thu/geometry-function-lab/js/script.js, 19-Sambid-Rana/wk01/4-thu/javascript-bank/index.html, 19-Sambid-Rana/wk01/4-thu/javascript-bank/js/script.js, 19-Sambid-Rana/wk01/4-thu/the-cash-register/index.html, 19-Sambid-Rana/wk01/4-thu/the-cash-register/js/script.js
7
Wasn't able to complete JS Bank.  Struggled with finding on how to get similar string for CC Verification
Credit card verification
6-7 hours, mainly took time with CCV
=> Credit Card, Geometry, JS Bank, and Cash Register

06-Eugene-Teo/wk01/4-thu/index.html, 06-Eugene-Teo/wk01/4-thu/js-exercise-4-EugeneTeo-230323.js
6
Triangle - obtuse
Triangle - obtuse (incomplete)
2-3 hours
=> INCOMPLETE_creditcard_and_JSbank_wk01_thu

10-Jordan-Borg/wk01/5-fri/NYSubway/index.html, 10-Jordan-Borg/wk01/5-fri/NYSubway/js/NYSubway.js
9/10 I think I did the first part correctly, but was unable to get it working, I was very lost in this attempt.
Getting started seems to be always what I struggle with most
recap on everything
all
4-5hrs
=> Friday homework NYSubway

05-Dominic-Wong/wk01/4-thu/credit card validation/js/exercises.js, 05-Dominic-Wong/wk01/4-thu/jsbank/index.html, 05-Dominic-Wong/wk01/4-thu/jsbank/js/exercises.js, 05-Dominic-Wong/wk01/5-fri/MTALab/index.html, 05-Dominic-Wong/wk01/5-fri/MTALab/js/mta.js
- How difficult did you find this (out of 10)? (0 being no problems at all, 10 being impossible) 7
- Was there anything that you struggled with? n/a
- Is there any particular code you want me to look into? n/a
- Is there anything that you'd like some further information on? n/a
- Roughly how long did it take? 4hrs
=> COMPLETE wk01 fri hw 

17-Riley-Mercer/wk01/5-fri/trains/index.html, 17-Riley-Mercer/wk01/5-fri/trains/js/trains.js
5? Nothing particularly hard, just lots of steps
Integrating the prompts was more annoying than I thought it would be
N/A
N/A
Three to four hours
=> 100% Working MTA Lab - Including Prompts

07-Howard-Wang/wk01/4-thu/Geometry&Cash Register/index.html, 07-Howard-Wang/wk01/4-thu/Geometry&Cash Register/js/Geometry&CashRegister.js
- How difficult did you find this (out of 10)? (0 being no problems at all, 10 being impossible) 6/10
- Was there anything that you struggled with? bonus questions
- Roughly how long did it take? 2 hrs
=> Complete Homework for 23rd MARCH

11-Joshua-Spicer/wk01/3-wed/index.js
Updating homework as per CJ's Request.
=> Homework Update for WED

15-Maggie-Cameron/wk01/4-thu/objects/index.html, 15-Maggie-Cameron/wk01/4-thu/objects/js/exercises.js
8. 
It just generally took me ages to get any working code on the console. Once I did I moved quite quickly (by comparison) through the question. Then I reached the next question and the cycle continues! I think if I had lots of time I would be able to complete everything... eventually. 
I worked through until about 10:30pm last night although I spent a couple of hours catching up on things I didn't get done from Tuesday/Wednesday first. Was …
=> incomplete homework THUS

21-Tristan-Bartolome/wk01/4-thu/Objects/exercises.js, 21-Tristan-Bartolome/wk01/4-thu/Objects/index.html
-INCOMPLETE
*Ignore cashForCart2, i was testing it and forgot to comment it out*
- 7 (area of triangle was a 8) 
- i struggled with areaOf so i just got the formula from online
- 6 hours
=> Objects Homework

01-Adam-Shuvalov/wk01/5-fri/MTA_Lab/MTA_Lab.js, 01-Adam-Shuvalov/wk01/5-fri/MTA_Lab/index.html
- How difficult did you find this (out of 10)? 6/10
- Was there anything that you struggled with? I wasn't sure how to allow the user to insert the array name into a prompt box as a string
- Is there any particular code you want me to look into? line 19-33 if theres a better way I can represent an array as a string
- Roughly how long did it take? 6 hours
=> MTA LAB COMPLETE Adam Shuvalov

18-Roxanne-Liu/wk01/3-wed/arrayAndFunctions/js/answer.js, 18-Roxanne-Liu/wk01/3-wed/arrayAndFunctions/question.text, 18-Roxanne-Liu/wk01/4-thu/GeometryFunctionLab/js/answer.js, 18-Roxanne-Liu/wk01/4-thu/GeometryFunctionLab/question.text, 18-Roxanne-Liu/wk01/5-fri/MTALab/indext.html, 18-Roxanne-Liu/wk01/5-fri/MTALab/js/answer.js, 18-Roxanne-Liu/wk01/5-fri/MTALab/question.text
=> updated W1_Wed_22_Mar_2023

22-Victor-Worobec/wk01/5-fri/MTA-lab/index.html, 22-Victor-Worobec/wk01/5-fri/MTA-lab/js/exercises.js
_If you had no problems you can just leave it empty
6
Coding without planning.
About 4 hrs
=> MTA-Lab Homework - Complete (with prompts)

09-James-Holton/wk01/5-fri/MTALab/index.html, 09-James-Holton/wk01/5-fri/MTALab/js/MTALab.js
7
at first I was creating a lot nested loops and struggled making a loop that works both ways and for any number of stops
6 hours if you include the time I spent on my non-functional draft.
1-2 hours after figuring out how to remove the need for nested loops and how to assign values.
=> MTALab Task

11-Joshua-Spicer/wk01/5-fri/index5.html, 11-Joshua-Spicer/wk01/5-fri/index5.js
9 hours including research and revision.
=> Friday_Homework

02-Akiko-Yamasaki/wk01/5-fri/MTA/index.html, 02-Akiko-Yamasaki/wk01/5-fri/MTA/js/main.js, 02-Akiko-Yamasaki/wk01/5-fri/MTA/js/plan.md
Imcomplete. worked on planing in .md file, broke down the task to small tasks, first few functions are written
10
Planning on how to work on a big task. took a whole day to figure out the small tasks I can start on
11 hours, but mainly working on breaking down the tasks and googling
=> MTA homework plan and code

03-Darcy-Mansfield/wk01/5-fri/subway/index.html, 03-Darcy-Mansfield/wk01/5-fri/subway/js/subway.js
7
Just figuring out the order of things, after that the code wasn't too complicated.
Nope
Negative
Minus procrastination, probably around 4 hours ( most of which was just working it out in my head )
=> GitHub Subway weekend homework

20-Stuart-Cannone/wk01/5-fri/homework/index.html, 20-Stuart-Cannone/wk01/5-fri/homework/js/Day5homework.js
Incomplete
- 8/10
- Getting all the stations to link 
- 6 hours 
-
=> MTA Attempt 1

04-Dineth-Rajapakse/wk01/5-fri/index.html, 04-Dineth-Rajapakse/wk01/5-fri/js/MTALab.js
- How difficult did you find this (out of 10)? (0 being no problems at all, 10 being impossible) 10 - still incomplete
- Was there anything that you struggled with? all of it :)
- Roughly how long did it take? 5 hrs (spent a lot of time revising JS to lock in what was covered in class for week 1)
=> INCOMPLETE MTA

21-Tristan-Bartolome/wk01/5-fri/Subway/.vscode/launch.json, 21-Tristan-Bartolome/wk01/5-fri/Subway/exercises.js, 21-Tristan-Bartolome/wk01/5-fri/Subway/index.html
had a lot of trouble with MTA-Lab in general.
*INCOMPLETE*
- 9
- for the most part i was quite stuck on each section, but once i got onto switching lines and going back down the line i couldn't figure it out 
- line 35-44: i believe something is outputting undefined but i couldn't find
- like about almost the whole weekend
=> “MTA_LABS_HOMEWORK”

07-Howard-Wang/wk01/5-fri/Plan/index.html, 07-Howard-Wang/wk01/5-fri/Plan/js/plan.js
=> Completed Homework for week1 Friday TripPlanner

19-Sambid-Rana/wk01/5-fri/index.html, 19-Sambid-Rana/wk01/5-fri/js/script.js
9
Everything
Haha, the entire script.js file
loops - where can I practice loops besides codewars?
=> MTA Lab First Attempt- Fail

12-Joshua-Ling/wk02/1-mon/html-labs/brooklyn/css/style.css, 12-Joshua-Ling/wk02/1-mon/html-labs/brooklyn/index.html, 12-Joshua-Ling/wk02/1-mon/html-labs/busyhands/css/normalize.css, 12-Joshua-Ling/wk02/1-mon/html-labs/busyhands/css/reset.css, 12-Joshua-Ling/wk02/1-mon/html-labs/busyhands/css/style.css, 12-Joshua-Ling/wk02/1-mon/html-labs/busyhands/index.html
I didn't know how to make the button go next to the text in busy hands.
I also didn't know how to fit the bottom of the footer in busy hands.
I also didnt know how to expand the background for busy hands without effecting the text margins.
- 7
- CSS
- Busy hands
- how to design css so that it's responsive to screen. 
- 2-3hours
=> HTML/CSS Brooklyn and Busy Hands

06-Eugene-Teo/wk01/5-fri/MTA_train_240323.js, 06-Eugene-Teo/wk01/5-fri/index.html
10 
any hints on how to proceed with the first few steps
=> INCOMPLETE MTA_240323

15-Maggie-Cameron/wk02/2-tue/css/Trivia/trivia.css, 15-Maggie-Cameron/wk02/2-tue/css/Trivia/trivia_index.html, 15-Maggie-Cameron/wk02/2-tue/css/hometown/hometown_website.css, 15-Maggie-Cameron/wk02/2-tue/css/hometown/index.html, 15-Maggie-Cameron/wk02/2-tue/css/index.html, 15-Maggie-Cameron/wk02/2-tue/css/website.css
8
Yes as you can see from the websites I am unable to get the <p> in the correct location. I perhaps incorrectly misheard Joel when he said to not mess with the position where possible. Everything I could find on google said to use float (which I thought Joel said not to do). 
the above
- Roughly how long did it take? 
tooo many hours :(
=> INCOMPLETE_WEBSITES_

04-Dineth-Rajapakse/wk02/3-wed/css/catwalk.css, 04-Dineth-Rajapakse/wk02/3-wed/index.html, 04-Dineth-Rajapakse/wk02/3-wed/js/catwalk.js
- How difficult did you find this (out of 10)? (0 being no problems at all, 10 being impossible) had to do a bit of research but was enjoyable. maybe my favourite hmw so far. 7/10
- Was there anything that you struggled with? yeah getting the cat to reset at position 0
- Roughly how long did it take?  4 hrs. perhaps way too long lol
=> Complete w/o bonus Cat Walk

17-Riley-Mercer/wk02/3-wed/catdance/css/css.css, 17-Riley-Mercer/wk02/3-wed/catdance/index.html, 17-Riley-Mercer/wk02/3-wed/catdance/js/js.js
8
I could not work out how to make the code repeat. 
No thank you
Provided this is not 'that' important further into the course, no thank you.
2-3 hours?
=> Cat Dance Complete, goes up and back once

05-Dominic-Wong/wk02/3-wed/catwalk/index.html, 05-Dominic-Wong/wk02/3-wed/catwalk/js/catwalk.js
- How difficult did you find this (out of 10)? (0 being no problems at all, 10 being impossible) 5
- Roughly how long did it take? 1hr
=> complete wk02 wed (incomplete bonuses)

15-Maggie-Cameron/wk02/3-wed/walking_cat/exercises.js, 15-Maggie-Cameron/wk02/3-wed/walking_cat/index.html, 15-Maggie-Cameron/wk02/3-wed/walking_cat/style.css
6
managed to get the cat walking across the screen and stop easily, could not figure out how to have it either loop from the start or turn around and walk back
- Roughly how long did it take? 3 hours
=> COMPLETE_ISH_CROSS_SCREEN_ONCE

20-Stuart-Cannone/wk02/3-wed/walking/css/walkingcat.css, 20-Stuart-Cannone/wk02/3-wed/walking/index.html, 20-Stuart-Cannone/wk02/3-wed/walking/js/walkingcat.js
Complete to the point of moving and reversing 
- 5/10
- Adding more interactivity, i wanted a text box to come out on the bottom of this page when the cat reached the end of the window saying get me out of this box but couldnt get it to work
- 2 hours
=> WalkingCat

11-Joshua-Spicer/wk02/3-wed/index.html, 11-Joshua-Spicer/wk02/3-wed/script.js
=> Moving Cat Homework

07-Howard-Wang/wk02/2-tue/larry-wall/page1/css/page1.css, 07-Howard-Wang/wk02/2-tue/larry-wall/page1/index.html, 07-Howard-Wang/wk02/2-tue/larry-wall/page2/css/page2.css, 07-Howard-Wang/wk02/2-tue/larry-wall/page2/index.html, 07-Howard-Wang/wk02/2-tue/larry-wall/page3/css/page3.css, 07-Howard-Wang/wk02/2-tue/larry-wall/page3/index.html, 07-Howard-Wang/wk02/3-wed/cat-walk/index.html, 07-Howard-Wang/wk02/3-wed/cat-walk/js/cat-walk.js
=> Homework for week2 Tuesday

05-Dominic-Wong/wk02/4-thu/about-me/index.html, 05-Dominic-Wong/wk02/4-thu/about-me/js/aboutme.js, 05-Dominic-Wong/wk02/4-thu/about-me/js/jquery.js, 05-Dominic-Wong/wk02/4-thu/book-list/css/style.css, 05-Dominic-Wong/wk02/4-thu/book-list/index.html, 05-Dominic-Wong/wk02/4-thu/book-list/js/book.js, 05-Dominic-Wong/wk02/4-thu/book-list/js/jquery.js, 05-Dominic-Wong/wk02/4-thu/calculator/index.html, 05-Dominic-Wong/wk02/4-thu/calculator/js/calculator.js, 05-Dominic-Wong/wk02/4-thu/calculator/js/jquery.js, 05-Dominic-Wong/wk02/4-thu/madlibs/index.html, 05-Dominic-Wong/wk02/4-thu/madlibs/js/jquery.js, 05-Dominic-Wong/wk02/4-thu/madlibs/js/madlibs.js
- How difficult did you find this (out of 10)? (0 being no problems at all, 10 being impossible) 2
- Roughly how long did it take? not long
=> complete wk02 thur hw

09-James-Holton/wk02/1-mon/html-labs/html-labs/busyhands/css/style.css, 09-James-Holton/wk02/1-mon/html-labs/html-labs/busyhands/readme.html, 09-James-Holton/wk02/1-mon/html-labs/html-labs/ecardly/css/style.css, 09-James-Holton/wk02/1-mon/html-labs/html-labs/ecardly/index.html, 09-James-Holton/wk02/2-tue/Computer-fansite/page1/js/fansite.js, 09-James-Holton/wk02/4-thu/jQuery/Books/css/books.css, 09-James-Holton/wk02/4-thu/jQuery/Books/index.html, 09-James-Holton/wk02/4-thu/jQuery/Books/js/books.js, 09-James-Holton/wk02/4-thu/jQuery/Calculator/css/calculator.css, 09-James-Holton/wk02/4-thu/jQuery/Calculator/index.html, 09-James-Holton/wk02/4-thu/jQuery/Calculator/js/calculator.js, 09-James-Holton/wk02/4-thu/jQuery/MadLibs/css/madlibs.css, 09-James-Holton/wk02/4-thu/jQuery/MadLibs/index.html, 09-James-Holton/wk02/4-thu/jQuery/MadLibs/js/madlibs.js, 09-James-Holton/wk02/4-thu/jQuery/about-me/css/aboutme.css, 09-James-Holton/wk02/4-thu/jQuery/about-me/index.html, 09-James-Holton/wk02/4-thu/jQuery/about-me/js/aboutme.js, 09-James-Holton/wk02/4-thu/jQuery/jQuery.js
jQuery was not difficult but had to research the methods used. With the web pages it took me a couple hours.
I wasn't sure if we were supposed to add onto the ecardly webpage but it only provided us with one screenshot of the finalised product.
=> All web SC's and jQuery

20-Stuart-Cannone/wk02/4-thu/aboutme/index.html, 20-Stuart-Cannone/wk02/4-thu/aboutme/js/aboutme.js, 20-Stuart-Cannone/wk02/4-thu/aboutme/js/jquery-3.6.4.js, 20-Stuart-Cannone/wk02/4-thu/books/index.html, 20-Stuart-Cannone/wk02/4-thu/books/js/books.js, 20-Stuart-Cannone/wk02/4-thu/books/js/jquery-3.6.4.js, 20-Stuart-Cannone/wk02/4-thu/calculator/index.html, 20-Stuart-Cannone/wk02/4-thu/calculator/js/calculator.js, 20-Stuart-Cannone/wk02/4-thu/calculator/js/jquery-3.6.4.js, 20-Stuart-Cannone/wk02/4-thu/madlibs/index.html, 20-Stuart-Cannone/wk02/4-thu/madlibs/js/jquery-3.6.4.js, 20-Stuart-Cannone/wk02/4-thu/madlibs/js/madlibs.js
complete to half way through the calculator
- 7/10, easier as less code to write but challenging to learn the new way to do things 
- the deeper mathematical section of the calculator 
- 2 hours
=> Jquery Exercises

13-Karen-Liang/wk02/4-thu/about-me/css/aboutme.css, 13-Karen-Liang/wk02/4-thu/about-me/index.html, 13-Karen-Liang/wk02/4-thu/about-me/js/aboutme.js, 13-Karen-Liang/wk02/4-thu/about-me/js/jquery.js, 13-Karen-Liang/wk02/4-thu/button/css/style.css, 13-Karen-Liang/wk02/4-thu/button/index.html, 13-Karen-Liang/wk02/4-thu/button/js/exercise.js, 13-Karen-Liang/wk02/4-thu/button/js/jquery.js, 13-Karen-Liang/wk02/4-thu/mad-libs/index.html, 13-Karen-Liang/wk02/4-thu/mad-libs/js/jquery.js, 13-Karen-Liang/wk02/4-thu/mad-libs/js/mad-libs.js
=> COMPLETE - mad libs, about me and created a toggle botton with jQuery

17-Riley-Mercer/wk02/4-thu/aboutme/index.html, 17-Riley-Mercer/wk02/4-thu/aboutme/js/js.js, 17-Riley-Mercer/wk02/4-thu/booklist/index.html, 17-Riley-Mercer/wk02/4-thu/booklist/js/js.js, 17-Riley-Mercer/wk02/4-thu/calcs/index.html, 17-Riley-Mercer/wk02/4-thu/calcs/js/js.js, 17-Riley-Mercer/wk02/4-thu/madlibs/index.html, 17-Riley-Mercer/wk02/4-thu/madlibs/js/js.js
- 10
- I could not work out how to iterate through the booklist array correctly. As a result I could not complete this section.
- I don't think I have enough code to make it worth it. A working copy of the code might be beneficial.
- As above.
- 3-4 hours? Some time was wasted in frustration.
=> Could not complete final part

07-Howard-Wang/wk02/4-thu/cat-walk/index.html, 07-Howard-Wang/wk02/4-thu/cat-walk/js/cat-walk.js, 07-Howard-Wang/wk02/4-thu/cat-walk/js/jquery.js
=> Homework for week2 Thursday

04-Dineth-Rajapakse/wk04/2-tue/MortgageCalculator.rb, 04-Dineth-Rajapakse/wk04/2-tue/calculator.rb
- How difficult did you find this (out of 10)? 6
- Is there any particular code you want me to look into? is there a way i can make my code DRYer?
- Roughly how long did it take? 1.5 hrs!
=> Final calculator

03-Darcy-Mansfield/wk04/2-tue/calculator.rb
4, but didn't get into any of the bonus stuff
Nope
Nope
Nope
< 1 hour
=> Calculator Ruby

13-Karen-Liang/wk04/2-tue/bmi-calculator.rb, 13-Karen-Liang/wk04/2-tue/calculator.rb
=> COMPLETE_wk04 tue homework

16-Ramez-Al-Siddiq/wk04/2-tue/calculator.rb
- How difficult did you find this (out of 10)? (0 being no problems at all, 10 being impossible) - 3
- Roughly how long did it take? 1.5 hours
=> COMPLETE calculator hw apart from bonus 11/04/2023

02-Akiko-Yamasaki/wk04/2-tue/calculator.rb
only the phase 1
- 8
- where to place code of lines
- 3 hours
=> ruby calculator

22-Victor-Worobec/wk04/2-tue/bmi-calculator.rb, 22-Victor-Worobec/wk04/2-tue/calculator.rb, 22-Victor-Worobec/wk04/2-tue/mortgage-calculator.rb, 22-Victor-Worobec/wk04/2-tue/ruby-repl.rb, 22-Victor-Worobec/wk04/2-tue/trip-calculator.rb
=> Ruby Homework - Complete

15-Maggie-Cameron/wk04/2-tue/BMI_calculator.rb, 15-Maggie-Cameron/wk04/2-tue/calculator.rb
6
I wasn't able to get the BMI calculator to restart when it had finished running - it quits after each use 
2 hours
=> RUBY_HOMEWORK INCOMPLETE BONUS (WORKING CALC + BMI)

06-Eugene-Teo/wk04/2-tue/calculator_exercise.rb
5
got stuck with trying to puts the results for a bit
- feel like entire code can be shortened to a function, since the only variable is the operator
- 2hrs. unfamiliarity with syntaxes etc
=> wk04_rbcalc_incomplete

19-Sambid-Rana/wk04/1-mon/calculator.rb
=> Calculator using Ruby

21-Tristan-Bartolome/wk04/2-tue/calculator/calculator.rb
- 4 struggled a bit before mark helped me, and then the rest was pretty easy
bonus was hard tho, i didn't know where to start haha
- about 2 hours
=> Homework complete but bonus incomplete

18-Roxanne-Liu/wk04/2-tue/BMI_Calculator.rb, 18-Roxanne-Liu/wk04/2-tue/Mortgage_Calculator.rb, 18-Roxanne-Liu/wk04/2-tue/Trip_Calculator.rb, 18-Roxanne-Liu/wk04/2-tue/calculator.rb, 18-Roxanne-Liu/wk04/2-tue/repl.rb
=> W4_Tue_11_Apr

13-Karen-Liang/wk04/3-wed/mta.rb, 13-Karen-Liang/wk04/3-wed/mta_dry.rb
=> COMPLETE_mta ruby

20-Stuart-Cannone/wk04/1-mon/calculator.rb, 20-Stuart-Cannone/wk04/2-tue/calculator.rb
Partially complete
- 6/10
- The more complex calculator especially the BMI
- 1.5 hours
=> Ruby Calculator 

22-Victor-Worobec/wk04/3-wed/mta-lab.rb
6
Parsing variables into functions. Used interpolation on string literal in arguments at first but it looked weird. Eventually switched to 'to_sym'.
7 hours
=> Ruby MTA-Lab - Complete

06-Eugene-Teo/wk04/2-tue/calculator_exercise.rb, 06-Eugene-Teo/wk04/3-wed/MTA_ruby.rb
- 5-6/10
mentioned in code # in MTA labs at the bottom. Have not completed user input, and put statement having [] and "" of station arrays. 
2-3 hours
=> revised phase 1 complete calculator + MTA labs ruby

14-Kee-Ming-Brandon/wk04/2-tue/calculator.rb, 14-Kee-Ming-Brandon/wk04/2-tue/do-it-yourself.rb, 14-Kee-Ming-Brandon/wk04/3-wed/mta.rb
8
Switching from js to rb, which is normal
- 
- 
Aprox. 30mins. Spent more time to review content for the day.
=> COMPLETE wk04 2-tue HW calculator WITHOUT bonus

02-Akiko-Yamasaki/wk04/2-tue/calculator.rb, 02-Akiko-Yamasaki/wk04/3-wed/mtl/mtl.rb
it is not completed, i have worked out travel on each line without changing trains
- 8
- 3 hours
=> mtl with ruby

16-Ramez-Al-Siddiq/wk04/3-wed/mta-lab/mta-lab.rb
- How difficult did you find this (out of 10)? (0 being no problems at all, 10 being impossible) - 7
- Was there anything that you struggled with? - my subway object was considered out of scope and I had difficulty creating a global variable - I thought adding a '$' before would work but I had to manually pass it through my methods. 
- Roughly how long did it take? 3 hours
=> COMPLETE MTA Lab 12/04/2023

23-Yosiyas-Debessay/wk04/2-tue/calculator.rb, 23-Yosiyas-Debessay/wk04/3-wed/mta.rb
- How difficult did you find this (out of 10)? (0 being no problems at all, 10 being impossible) 10
=> mta using ruby

03-Darcy-Mansfield/wk04/3-wed/mta.rb
6
Not being able to define the mta hash outside the method
Nope
Any way to define the hash outside the method to be used in the method?
2 hours
=> COMPLETE mta Ruby homework

07-Howard-Wang/wk04/2-tue/calculator.rb
=> Homework for week4 Tuesday

17-Riley-Mercer/wk04/3-wed/trains.rb
=> Mostly complete

10-Jordan-Borg/wk04/3-wed/subway.rb
7/10 
this legit gave me a headache. 
I feel ruby is a million times easier than Javascript but still not sinking into my brain.
=> Wednesday homework

05-Dominic-Wong/wk04/3-wed/mta-again/brief.md, 05-Dominic-Wong/wk04/3-wed/mta-again/mta.rb
- How difficult did you find this (out of 10)? (0 being no problems at all, 10 being impossible) MTA logic wasn't too long.  Taking inputs from the terminal and using it to run the function took suprisingly long...
- Is there anything that you'd like some further information on? error handling 
=> complete wk04 wed hw

07-Howard-Wang/wk04/3-wed/mta.rb
=> Completed Homework for week4 Wednesday

22-Victor-Worobec/wk04/4-thu/books/main.rb, 22-Victor-Worobec/wk04/4-thu/books/views/home.erb, 22-Victor-Worobec/wk04/4-thu/books/views/image.erb, 22-Victor-Worobec/wk04/4-thu/books/views/layout.erb
=> Books API Homework - Complete

20-Stuart-Cannone/wk04/4-thu/Book Covers/main.rb, 20-Stuart-Cannone/wk04/4-thu/Book Covers/public/css/books.css, 20-Stuart-Cannone/wk04/4-thu/Book Covers/views/cover.erb, 20-Stuart-Cannone/wk04/4-thu/Book Covers/views/home.erb, 20-Stuart-Cannone/wk04/4-thu/Book Covers/views/layout.erb
Complete working but minimal CSS styling 
- 4/10
- 1.5 hours
=> Book Cover Finder

19-Sambid-Rana/wk04/4-thur/books-sinatra/main.rb, 19-Sambid-Rana/wk04/4-thur/books-sinatra/public/css/style.css, 19-Sambid-Rana/wk04/4-thur/books-sinatra/views/bookcover.erb, 19-Sambid-Rana/wk04/4-thur/books-sinatra/views/home.erb, 19-Sambid-Rana/wk04/4-thur/books-sinatra/views/layout.erb
line 14 from bookcover.erb, i was trying to use the key value parameter/argument but it only returns value. Is it because the method is only available for hash and not for strings?
=> Books-Sinatra

14-Kee-Ming-Brandon/wk04/4-thu/main.rb, 14-Kee-Ming-Brandon/wk04/4-thu/public/css/style.css, 14-Kee-Ming-Brandon/wk04/4-thu/views/home.erb, 14-Kee-Ming-Brandon/wk04/4-thu/views/layout.erb, 14-Kee-Ming-Brandon/wk04/4-thu/views/result.erb
=> COMPLETE wk04 4-thu HW basic book searcher

03-Darcy-Mansfield/wk04/4-thu/books/main.rb, 03-Darcy-Mansfield/wk04/4-thu/books/public/img/style.css, 03-Darcy-Mansfield/wk04/4-thu/books/views/book.erb, 03-Darcy-Mansfield/wk04/4-thu/books/views/home.erb, 03-Darcy-Mansfield/wk04/4-thu/books/views/layout.erb
7
understanding the connections between the files
3 hours
=> COMPLETE book info homework in ruby/sinatra

23-Yosiyas-Debessay/wk04/4-thu/bookcover/main.rb, 23-Yosiyas-Debessay/wk04/4-thu/bookcover/views/home.erb, 23-Yosiyas-Debessay/wk04/4-thu/bookcover/views/info.erb, 23-Yosiyas-Debessay/wk04/4-thu/bookcover/views/layout.erb
- How difficult did you find this (out of 10)? (0 being no problems at all, 10 being impossible).   10
- Was there anything that you struggled with? I struggled with everything. Ruby is really confusing ngl
- Roughly how long did it take?    couple of hours on and off the computer coz I kept getting frustrated and leaving hahaha
=> bookcover HW

16-Ramez-Al-Siddiq/wk04/4-thu/books/main.rb, 16-Ramez-Al-Siddiq/wk04/4-thu/books/public/css/books.css, 16-Ramez-Al-Siddiq/wk04/4-thu/books/views/home.erb, 16-Ramez-Al-Siddiq/wk04/4-thu/books/views/layout.erb
- How difficult did you find this (out of 10)? (0 being no problems at all, 10 being impossible) - 8
- Was there anything that you struggled with? - difficulty loading the book cover for a given book.
- Roughly how long did it take? 2.5 hours
=> INCOMPLETE Book Search 13/04/2023

15-Maggie-Cameron/wk04/4-thu/books/main.rb, 15-Maggie-Cameron/wk04/4-thu/books/views/book_preview.erb, 15-Maggie-Cameron/wk04/4-thu/books/views/home.erb, 15-Maggie-Cameron/wk04/4-thu/books/views/layout.erb
7
Yes. For once I was feeling v positive going into the homework and felt like I really understood it. I almost finished everything within perhaps an hour (new record!). Then I couldn't figure out how to wrap the image in image tags (everything I found online was for Ruby on rails and I wasn't sure what was correct). I worked on that for perhaps 3 more hours until i found the right combination lol. In the end my first attempt was so so close to being correct so that's something. 
- Is there anything that you'd like some further information …
=> book cover preview task complete

17-Riley-Mercer/wk04/5-fri/animaldb/database/butterflies/butterflies.sql, 17-Riley-Mercer/wk04/5-fri/animaldb/database/butterflies/create_butterflies.sql, 17-Riley-Mercer/wk04/5-fri/animaldb/database/butterflies/main.rb, 17-Riley-Mercer/wk04/5-fri/animaldb/database/butterflies/public/css/butterflies.css, 17-Riley-Mercer/wk04/5-fri/animaldb/database/butterflies/views/butterflies_edit.erb, 17-Riley-Mercer/wk04/5-fri/animaldb/database/butterflies/views/butterflies_index.erb, 17-Riley-Mercer/wk04/5-fri/animaldb/database/butterflies/views/butterflies_new.erb, 17-Riley-Mercer/wk04/5-fri/animaldb/database/butterflies/views/butterflies_show.erb, 17-Riley-Mercer/wk04/5-fri/animaldb/database/butterflies/views/home.erb, 17-Riley-Mercer/wk04/5-fri/animaldb/database/butterflies/views/layout.erb, 17-Riley-Mercer/wk04/5-fri/animaldb/database/intro/animals.sql, 17-Riley-Mercer/wk04/5-fri/webby/db/cats.sql
I have had an issue with my SQLite3. When I attempt to run the commands to get my DB up and running it says: "stdin is not a tty".
I have looked through at least the first two pages of google results but nothing seems to really fit my circumstance. I think this is an issue arising from my Windows / linux set up, but I am not sure.
You can see my different attempts at getting this to work in my homework file, with increasingly derranged names. Eventually I gave up, copied the provided code and annotated it with comments from the GitBook. This is so when I eventually get it working I should know roughly what I am looking at.
Honestly I am not sure. Many hours!
=> I have suffered catastrophic failure

23-Yosiyas-Debessay/wk04/5-fri/cars/cars.css, 23-Yosiyas-Debessay/wk04/5-fri/cars/create_cars.sql, 23-Yosiyas-Debessay/wk04/5-fri/cars/main.rb, 23-Yosiyas-Debessay/wk04/5-fri/views/cars_edit.erb, 23-Yosiyas-Debessay/wk04/5-fri/views/cars_index.erb, 23-Yosiyas-Debessay/wk04/5-fri/views/cars_new.erb, 23-Yosiyas-Debessay/wk04/5-fri/views/cars_show.erb, 23-Yosiyas-Debessay/wk04/5-fri/views/home.erb, 23-Yosiyas-Debessay/wk04/5-fri/views/layout.erb
- How difficult did you find this (out of 10)? (0 being no problems at all, 10 being impossible) 
=> cars ruby hw

07-Howard-Wang/wk04/4-thu/bookcover/main.rb, 07-Howard-Wang/wk04/4-thu/bookcover/public/css/cover.css, 07-Howard-Wang/wk04/4-thu/bookcover/views/home.erb, 07-Howard-Wang/wk04/4-thu/bookcover/views/info.erb, 07-Howard-Wang/wk04/4-thu/bookcover/views/layout.erb
- Was there anything that you struggled with? keep forgetting to upload
=> Completed Homework for week4 Thursday - keep forgetting to upload

13-Karen-Liang/wk05/3-wed/flix/config/routes.rb, 13-Karen-Liang/wk07/1-mon/css/book.css, 13-Karen-Liang/wk07/1-mon/index.html, 13-Karen-Liang/wk07/1-mon/js/books.js
=> Wednesday hw minor update to routes page

16-Ramez-Al-Siddiq/wk07/1-mon/google-books-search/index.html, 16-Ramez-Al-Siddiq/wk07/1-mon/google-books-search/js/google-books-search.js
- How difficult did you find this (out of 10)? (0 being no problems at all, 10 being impossible) - 5
- Roughly how long did it take? 1.5 hours
=> COMPLETE Google Books Search AJAX Exercise 1/05/2023

12-Joshua-Ling/wk07/1-mon/css/css.css, 12-Joshua-Ling/wk07/1-mon/index.html, 12-Joshua-Ling/wk07/1-mon/js/books.js
=> week 7 mon homework

14-Kee-Ming-Brandon/wk07/1-mon/google-book-search/css/style.css, 14-Kee-Ming-Brandon/wk07/1-mon/google-book-search/index.html, 14-Kee-Ming-Brandon/wk07/1-mon/google-book-search/js/books.js, 14-Kee-Ming-Brandon/wk07/1-mon/google-book-search/js/jquery.js
=> COMPLETE HW wk07 1-mon Google book searcher

11-Joshua-Spicer/wk07/1-mon/google_books/index.html, 11-Joshua-Spicer/wk07/1-mon/google_books/js/books.js, 11-Joshua-Spicer/wk07/1-mon/google_books/style.css
Monday's Homework. 
Difficulty 6/10
=> Monday Book Homework

10-Jordan-Borg/wk07/1-mon/googbook/books.css, 10-Jordan-Borg/wk07/1-mon/googbook/index.html, 10-Jordan-Borg/wk07/1-mon/googbook/js/books.js
7/10 
wasn't able to wrap my head around JSON & XHR just yet,
=> Mondays Homework

17-Riley-Mercer/wk07/1-mon/books/css/books.css, 17-Riley-Mercer/wk07/1-mon/books/index.html, 17-Riley-Mercer/wk07/1-mon/books/js/books.js, 17-Riley-Mercer/wk07/1-mon/books/js/jquery.js
- How difficult did you find this (out of 10)? (0 being no problems at all, 10 being impossible) 2
- Was there anything that you struggled with? N/A
- Is there any particular code you want me to look into? N/A
- Is there anything that you'd like some further information on? N/A
- Roughly how long did it take? ~1 hour
=> Complete Homework

05-Dominic-Wong/wk07/1-mon/books/css/books.css, 05-Dominic-Wong/wk07/1-mon/books/index.html, 05-Dominic-Wong/wk07/1-mon/books/js/books.js
=> wk07 mon hw complete

21-Tristan-Bartolome/wk07/1-mon/Book-search/index.html, 21-Tristan-Bartolome/wk07/1-mon/Book-search/js/books.js
4
struggled with getting thumbnail to show
2 hours
=> homework complete

22-Victor-Worobec/wk07/1-mon/index.html, 22-Victor-Worobec/wk07/1-mon/js/index.js
=> Books-AJAX Homework - Complete

06-Eugene-Teo/wk07/1-mon/numbers/css/style.css, 06-Eugene-Teo/wk07/1-mon/numbers/index.html, 06-Eugene-Teo/wk07/1-mon/numbers/js/numbers.js
not related to this exercise, but regarding yesterday's function callbacks, and using a function as an argument. 
const xxx = function ( function ) {
}
found it a little challenging to get the concept
=> complete google books cover + description

20-Stuart-Cannone/wk07/1-mon/AJAX/css/books.css, 20-Stuart-Cannone/wk07/1-mon/AJAX/index.html, 20-Stuart-Cannone/wk07/1-mon/AJAX/js/books.js
Complete
- 7/10
- the google books api just sucks and index [0} is not always the right book and requires way too much configuration to make a list appear of books that match similar titles 
- 2 hours
=> Google Books

15-Maggie-Cameron/wk07/1-mon/books/index.html, 15-Maggie-Cameron/wk07/1-mon/books/js/books.js
8
Yes I wasn't able to get it working as I struggled for a long time with what to do with the data once I retrieved it. I think I kind of forgot how to do things in javascript. I initially was pretty close to Joel's solution using dot notation however the longer I worked on it the worse it got. I think I should be back into it by today though (hopefully!!). 
- Roughly how long did it take? 3 hrs
=> complete book cover search

21-Tristan-Bartolome/wk07/2-tue/api-jquery/css/style.css, 21-Tristan-Bartolome/wk07/2-tue/api-jquery/index.html, 21-Tristan-Bartolome/wk07/2-tue/api-jquery/js/api.js, 21-Tristan-Bartolome/wk07/2-tue/api-jquery/js/jquery.js
=> HW-complete

22-Victor-Worobec/wk07/2-tue/css/index.css, 22-Victor-Worobec/wk07/2-tue/index.html, 22-Victor-Worobec/wk07/2-tue/js/index.js, 22-Victor-Worobec/wk07/2-tue/js/jquery.js
5
Learning how to use some APIs
8 hours
=> API-AJAX Homework - Complete

06-Eugene-Teo/wk07/1-mon/numbers/index.html, 06-Eugene-Teo/wk07/1-mon/numbers/js/numbers.js
=> working search function

15-Maggie-Cameron/wk07/2-tue/cat_apis/cat_apis.html, 15-Maggie-Cameron/wk07/2-tue/cat_apis/js/jquery.js, 15-Maggie-Cameron/wk07/2-tue/cat_apis/js/js.js, 15-Maggie-Cameron/wk07/2-tue/joke machine/index.html, 15-Maggie-Cameron/wk07/2-tue/joke machine/js/jquery.js, 15-Maggie-Cameron/wk07/2-tue/joke machine/js/js.js
6
Once I managed to find working APIs I was able to do the homework confidently. Each time I tried to do a new model I ran into problems with so many APIs though. I wasn't able to get a key working. I don't know enough about APIs to know if it was me or some other issue. Hopefully we will go over that this week. 
4 hrs (mainly trying to find APIS i could use!!)
=> complete homework 2 pages

05-Dominic-Wong/wk07/1-mon/books/js/books.js, 05-Dominic-Wong/wk07/2-tue/api-hw/css/stylesheet.css, 05-Dominic-Wong/wk07/2-tue/api-hw/index.html, 05-Dominic-Wong/wk07/2-tue/api-hw/js/jquery.js, 05-Dominic-Wong/wk07/2-tue/api-hw/js/nasa.js
=> complete wk7 tue hw

10-Jordan-Borg/wk07/2-tue/Public_API/index.html, 10-Jordan-Borg/wk07/2-tue/Public_API/js/jquery.js, 10-Jordan-Borg/wk07/2-tue/Public_API/js/publicapi.js
I was unable to get numbers and images to work, but text was fine
=> Tuesdays Homework

17-Riley-Mercer/wk07/2-tue/sites/books.html, 17-Riley-Mercer/wk07/2-tue/sites/css/basic.css, 17-Riley-Mercer/wk07/2-tue/sites/index.html, 17-Riley-Mercer/wk07/2-tue/sites/js/books.js, 17-Riley-Mercer/wk07/2-tue/sites/js/jquery.js, 17-Riley-Mercer/wk07/2-tue/sites/js/plays.js, 17-Riley-Mercer/wk07/2-tue/sites/js/pokemons.js, 17-Riley-Mercer/wk07/2-tue/sites/plays.html, 17-Riley-Mercer/wk07/2-tue/sites/pokemons.html
- How difficult did you find this (out of 10)? (0 being no problems at all, 10 being impossible) 5 (only the Shakespear thing)
- Was there anything that you struggled with? Nothing in particular
- Is there any particular code you want me to look into? I thought the switch / case code was pretty slick
- Is there anything that you'd like some further information on? No thank you
- Roughly how long did it take? I am honestly not sure. I was lost in the sauce.
=> Tuesday Homework

23-Yosiyas-Debessay/wk07/1-mon/maps/js/maps.js, 23-Yosiyas-Debessay/wk07/2-tue/exo-planet/index.html, 23-Yosiyas-Debessay/wk07/2-tue/exo-planet/js/exo.js, 23-Yosiyas-Debessay/wk07/2-tue/exo-planet/js/jquery.js, 23-Yosiyas-Debessay/wk07/2-tue/mars-rover-photos/index.html, 23-Yosiyas-Debessay/wk07/2-tue/mars-rover-photos/js/jquery.js, 23-Yosiyas-Debessay/wk07/2-tue/mars-rover-photos/js/rover.js, 23-Yosiyas-Debessay/wk07/2-tue/nasa-images/index.html, 23-Yosiyas-Debessay/wk07/2-tue/nasa-images/js/jquery.js, 23-Yosiyas-Debessay/wk07/2-tue/nasa-images/js/nasa.js
- How difficult did you find this (out of 10)? (0 being no problems at all, 10 being impossible) 7
- Was there anything that you struggled with?  
The NASA images works, so when you type anything like "Space" and click search it brings up NASA's image of space. The rover images and Exo-planet are not working. The exo planet shows errors in the console and the rover doesn't show any errors but it doesn't work either.
- 
- Is there any particular code you want me to look into? The rover and the exo-planet search
- Roughly how long did it take? 3 hours-ish
=> NASS Exo Planet Homework

12-Joshua-Ling/wk07/2-tue/css/css.css, 12-Joshua-Ling/wk07/2-tue/index.html, 12-Joshua-Ling/wk07/2-tue/js/jquery.js, 12-Joshua-Ling/wk07/2-tue/js/js.js
=> week 7 tue homework

16-Ramez-Al-Siddiq/wk07/2-tue/apis/nasa/index.html, 16-Ramez-Al-Siddiq/wk07/2-tue/apis/nasa/js/jquery.js, 16-Ramez-Al-Siddiq/wk07/2-tue/apis/nasa/js/nasa.js, 16-Ramez-Al-Siddiq/wk07/2-tue/apis/pokemon/index.html, 16-Ramez-Al-Siddiq/wk07/2-tue/apis/pokemon/js/jquery.js, 16-Ramez-Al-Siddiq/wk07/2-tue/apis/pokemon/js/pokemon.js
- How difficult did you find this (out of 10)? (0 being no problems at all, 10 being impossible) - 7
- Roughly how long did it take? - 3.5 hours
=> COMPLETED NASA API jQuery AJAX Exercise - 2/05/2023

19-Sambid-Rana/wk07/day-1/ajax-readings/.vscode/settings.json, 19-Sambid-Rana/wk07/day-1/ajax-readings/index.html, 19-Sambid-Rana/wk07/day-1/ajax-readings/js/script.js, 19-Sambid-Rana/wk07/day-2/random-apis/.vscode/settings.json, 19-Sambid-Rana/wk07/day-2/random-apis/css/style.css, 19-Sambid-Rana/wk07/day-2/random-apis/index.html, 19-Sambid-Rana/wk07/day-2/random-apis/js/jquery.js, 19-Sambid-Rana/wk07/day-2/random-apis/js/script.js
=> Book Search -AJAX

14-Kee-Ming-Brandon/wk07/2-tue/api-homework/css/style.css, 14-Kee-Ming-Brandon/wk07/2-tue/api-homework/index.html, 14-Kee-Ming-Brandon/wk07/2-tue/api-homework/js/jquery.js, 14-Kee-Ming-Brandon/wk07/2-tue/api-homework/js/photos.js
=> COMPLETE wk07 2-tue HW RandomWord & pixabay API

06-Eugene-Teo/wk07/2-tue/disney-jquery/css/style.css, 06-Eugene-Teo/wk07/2-tue/disney-jquery/index.html, 06-Eugene-Teo/wk07/2-tue/disney-jquery/js/jquery.js, 06-Eugene-Teo/wk07/2-tue/disney-jquery/js/numbers.js
I believe there are some issues on data retrieval, not sure if my code is correct. Might have to redo it with a simpler and more consistent API...
Doesn't matter whatever search keywords, the results will always be the same, so maybe
https://disneyapi.dev/ this was the one I used
=> incomplete ajax API single page app

03-Darcy-Mansfield/wk07/3-wed/image-search/css/style.css, 03-Darcy-Mansfield/wk07/3-wed/image-search/index.html, 03-Darcy-Mansfield/wk07/3-wed/image-search/js/jquery.js, 03-Darcy-Mansfield/wk07/3-wed/image-search/js/search.js, 03-Darcy-Mansfield/wk07/3-wed/image-search/js/underscore.js
7
I think I got everything but there might be some bugs which I didn't think of
3 hours
=> complete flickr image search homework

12-Joshua-Ling/wk07/2-tue/index.html, 12-Joshua-Ling/wk07/2-tue/js/js.js, 12-Joshua-Ling/wk07/3-wed/image-search/index.html, 12-Joshua-Ling/wk07/3-wed/image-search/js/jquery.js, 12-Joshua-Ling/wk07/3-wed/image-search/js/search.js, 12-Joshua-Ling/wk07/3-wed/image-search/js/underscore.js
=> Wk 7 Wed Homework

05-Dominic-Wong/wk07/3-wed/image-search/index.html, 05-Dominic-Wong/wk07/3-wed/image-search/js/jquery.js, 05-Dominic-Wong/wk07/3-wed/image-search/js/search.js, 05-Dominic-Wong/wk07/3-wed/image-search/js/underscore.js
=> hw wk07 wed complete

11-Joshua-Spicer/wk07/2-tue/API_Application2.0/app.js, 11-Joshua-Spicer/wk07/2-tue/API_Application2.0/index.html, 11-Joshua-Spicer/wk07/2-tue/API_Application2.0/style.css
Tried various API's but I encountered errors with them. Found this cat API that is a free demo and I was able repurpose it for the homework assignment.
=> CAT API Webpage

17-Riley-Mercer/wk07/3-wed/image-search/.vscode/settings.json, 17-Riley-Mercer/wk07/3-wed/image-search/index.html, 17-Riley-Mercer/wk07/3-wed/image-search/js/jquery.js, 17-Riley-Mercer/wk07/3-wed/image-search/js/search.js, 17-Riley-Mercer/wk07/3-wed/image-search/js/underscore.js
I got lost in the sauce trying to make this fancy and use promises and other nerdy things. Once I realised that was outside of my skillset and just used the basic implementation as seen below it did not take long at all. 
- Roughly how long did it take? 3-3.5 hours
I would attempt the bonus, but have not done the quiz / recorded lecture component yet and not sure how long that will take.
=> Complete - no bonus

20-Stuart-Cannone/wk07/3-wed/image-search/index.html, 20-Stuart-Cannone/wk07/3-wed/image-search/js/jquery.js, 20-Stuart-Cannone/wk07/3-wed/image-search/js/search.js, 20-Stuart-Cannone/wk07/3-wed/image-search/js/underscore.js
i think its complete but not sure 
- 9/10
- pretty much all of it 
- 5 hours
=> Image Search

05-Dominic-Wong/wk07/4-thu/recursion-exercises/.gitignore, 05-Dominic-Wong/wk07/4-thu/recursion-exercises/floodIt-challenge/README.md, 05-Dominic-Wong/wk07/4-thu/recursion-exercises/floodIt-challenge/app.js, 05-Dominic-Wong/wk07/4-thu/recursion-exercises/floodIt-challenge/index.html, 05-Dominic-Wong/wk07/4-thu/recursion-exercises/floodIt-challenge/style.css, 05-Dominic-Wong/wk07/4-thu/recursion-exercises/package-lock.json, 05-Dominic-Wong/wk07/4-thu/recursion-exercises/package.json, 05-Dominic-Wong/wk07/4-thu/recursion-exercises/readme.md, 05-Dominic-Wong/wk07/4-thu/recursion-exercises/recursion.js, 05-Dominic-Wong/wk07/4-thu/recursion-exercises/test/index.js
- How difficult did you find this (out of 10)? (0 being no problems at all, 10 being impossible) That was very hard
=> hw wk07 complete partial

12-Joshua-Ling/wk07/4-thu/recursion-exercises/.gitignore, 12-Joshua-Ling/wk07/4-thu/recursion-exercises/floodIt-challenge/README.md, 12-Joshua-Ling/wk07/4-thu/recursion-exercises/floodIt-challenge/app.js, 12-Joshua-Ling/wk07/4-thu/recursion-exercises/floodIt-challenge/index.html, 12-Joshua-Ling/wk07/4-thu/recursion-exercises/floodIt-challenge/style.css, 12-Joshua-Ling/wk07/4-thu/recursion-exercises/package-lock.json, 12-Joshua-Ling/wk07/4-thu/recursion-exercises/package.json, 12-Joshua-Ling/wk07/4-thu/recursion-exercises/readme.md, 12-Joshua-Ling/wk07/4-thu/recursion-exercises/recursion.js, 12-Joshua-Ling/wk07/4-thu/recursion-exercises/test/index.js
=> Week 7 Thurs Homework

03-Darcy-Mansfield/wk07/4-thu/recursion-exercises/.gitignore, 03-Darcy-Mansfield/wk07/4-thu/recursion-exercises/floodIt-challenge/README.md, 03-Darcy-Mansfield/wk07/4-thu/recursion-exercises/floodIt-challenge/app.js, 03-Darcy-Mansfield/wk07/4-thu/recursion-exercises/floodIt-challenge/index.html, 03-Darcy-Mansfield/wk07/4-thu/recursion-exercises/floodIt-challenge/style.css, 03-Darcy-Mansfield/wk07/4-thu/recursion-exercises/package-lock.json, 03-Darcy-Mansfield/wk07/4-thu/recursion-exercises/package.json, 03-Darcy-Mansfield/wk07/4-thu/recursion-exercises/readme.md, 03-Darcy-Mansfield/wk07/4-thu/recursion-exercises/recursion.js, 03-Darcy-Mansfield/wk07/4-thu/recursion-exercises/test/index.js
8
coin flip and letter combo problems, couldn't  quite figure them out
4 hours
=> incomplete recursion homework

16-Ramez-Al-Siddiq/wk07/4-thu/recursion-exercises/.gitignore, 16-Ramez-Al-Siddiq/wk07/4-thu/recursion-exercises/floodIt-challenge/README.md, 16-Ramez-Al-Siddiq/wk07/4-thu/recursion-exercises/floodIt-challenge/app.js, 16-Ramez-Al-Siddiq/wk07/4-thu/recursion-exercises/floodIt-challenge/index.html, 16-Ramez-Al-Siddiq/wk07/4-thu/recursion-exercises/floodIt-challenge/style.css, 16-Ramez-Al-Siddiq/wk07/4-thu/recursion-exercises/package-lock.json, 16-Ramez-Al-Siddiq/wk07/4-thu/recursion-exercises/package.json, 16-Ramez-Al-Siddiq/wk07/4-thu/recursion-exercises/readme.md, 16-Ramez-Al-Siddiq/wk07/4-thu/recursion-exercises/recursion.js, 16-Ramez-Al-Siddiq/wk07/4-thu/recursion-exercises/test/index.js
- How difficult did you find this (out of 10)? (0 being no problems at all, 10 being impossible) - 8
- Roughly how long did it take? - 2.5 hours
=> INCOMPLETE - only managed findMax and factorial - 4/05/2023

23-Yosiyas-Debessay/wk07/4-thu/recursion-exercises/.gitignore, 23-Yosiyas-Debessay/wk07/4-thu/recursion-exercises/floodIt-challenge/README.md, 23-Yosiyas-Debessay/wk07/4-thu/recursion-exercises/floodIt-challenge/app.js, 23-Yosiyas-Debessay/wk07/4-thu/recursion-exercises/floodIt-challenge/index.html, 23-Yosiyas-Debessay/wk07/4-thu/recursion-exercises/floodIt-challenge/style.css, 23-Yosiyas-Debessay/wk07/4-thu/recursion-exercises/package-lock.json, 23-Yosiyas-Debessay/wk07/4-thu/recursion-exercises/package.json, 23-Yosiyas-Debessay/wk07/4-thu/recursion-exercises/readme.md, 23-Yosiyas-Debessay/wk07/4-thu/recursion-exercises/recursion.js, 23-Yosiyas-Debessay/wk07/4-thu/recursion-exercises/test/index.js
- How difficult did you find this (out of 10)? (0 being no problems at all, 10 being impossible) 8
- Was there anything that you struggled with? besides the first question , the rest were pretty hard in ym opinion. Had to get help from other students aswell to see how they did it. Couldn’t do the last one coz I had no ides hpw to.
=> Attempt at exercises

02-Akiko-Yamasaki/wk07/4-thu/recursion-exercises/.gitignore, 02-Akiko-Yamasaki/wk07/4-thu/recursion-exercises/floodIt-challenge/README.md, 02-Akiko-Yamasaki/wk07/4-thu/recursion-exercises/floodIt-challenge/app.js, 02-Akiko-Yamasaki/wk07/4-thu/recursion-exercises/floodIt-challenge/index.html, 02-Akiko-Yamasaki/wk07/4-thu/recursion-exercises/floodIt-challenge/style.css, 02-Akiko-Yamasaki/wk07/4-thu/recursion-exercises/package-lock.json, 02-Akiko-Yamasaki/wk07/4-thu/recursion-exercises/package.json, 02-Akiko-Yamasaki/wk07/4-thu/recursion-exercises/readme.md, 02-Akiko-Yamasaki/wk07/4-thu/recursion-exercises/recursion.js, 02-Akiko-Yamasaki/wk07/4-thu/recursion-exercises/test/index.js
attempted, first two got the green line from mpn test
- 9, think I understand the basic principles but applying it is challenging
-4hrs,  half of the time was researching on recursion.
=> recursions

09-James-Holton/wk07/4-thu/recursion-exercises/.gitignore, 09-James-Holton/wk07/4-thu/recursion-exercises/.gitignore:Zone.Identifier, 09-James-Holton/wk07/4-thu/recursion-exercises/floodIt-challenge/README.md, 09-James-Holton/wk07/4-thu/recursion-exercises/floodIt-challenge/README.md:Zone.Identifier, 09-James-Holton/wk07/4-thu/recursion-exercises/floodIt-challenge/app.js, 09-James-Holton/wk07/4-thu/recursion-exercises/floodIt-challenge/app.js:Zone.Identifier, 09-James-Holton/wk07/4-thu/recursion-exercises/floodIt-challenge/index.html, 09-James-Holton/wk07/4-thu/recursion-exercises/floodIt-challenge/index.html:Zone.Identifier, 09-James-Holton/wk07/4-thu/recursion-exercises/floodIt-challenge/style.css, 09-James-Holton/wk07/4-thu/recursion-exercises/floodIt-challenge/style.css:Zone.Identifier, 09-James-Holton/wk07/4-thu/recursion-exercises/package-lock.json, 09-James-Holton/wk07/4-thu/recursion-exercises/package-lock.json:Zone.Identifier, 09-James-Holton/wk07/4-thu/recursion-exercises/package.json, 09-James-Holton/wk07/4-thu/recursion-exercises/package.json:Zone.Identifier, 09-James-Holton/wk07/4-thu/recursion-exercises/readme.md, 09-James-Holton/wk07/4-thu/recursion-exercises/readme.md:Zone.Identifier, 09-James-Holton/wk07/4-thu/recursion-exercises/recursion.js, 09-James-Holton/wk07/4-thu/recursion-exercises/recursion.js:Zone.Identifier, 09-James-Holton/wk07/4-thu/recursion-exercises/test/index.js, 09-James-Holton/wk07/4-thu/recursion-exercises/test/index.js:Zone.Identifier
I struggled a lot with the coin loop and the letters loop. The letters only work when the array has 3 letters and is not dynamic. Recursive functions hard lol
=> recursive test

06-Eugene-Teo/wk07/4-thu/recursion-exercises/.gitignore, 06-Eugene-Teo/wk07/4-thu/recursion-exercises/floodIt-challenge/README.md, 06-Eugene-Teo/wk07/4-thu/recursion-exercises/floodIt-challenge/app.js, 06-Eugene-Teo/wk07/4-thu/recursion-exercises/floodIt-challenge/index.html, 06-Eugene-Teo/wk07/4-thu/recursion-exercises/floodIt-challenge/style.css, 06-Eugene-Teo/wk07/4-thu/recursion-exercises/package-lock.json, 06-Eugene-Teo/wk07/4-thu/recursion-exercises/package.json, 06-Eugene-Teo/wk07/4-thu/recursion-exercises/readme.md, 06-Eugene-Teo/wk07/4-thu/recursion-exercises/recursion.js, 06-Eugene-Teo/wk07/4-thu/recursion-exercises/test/index.js
10 for the last part 
letterCombinations
=> incomplete - letterCombinations

23-Yosiyas-Debessay/wk08/1-mon/NASASEARCH/src/components/ImageSearch.jsx, 23-Yosiyas-Debessay/wk08/1-mon/NASASEARCH/src/components/SearchForm.jsx
=> Updated version but still couldn't get it to work

12-Joshua-Ling/wk10/1-mon/express/index.js, 12-Joshua-Ling/wk10/1-mon/express/package-lock.json, 12-Joshua-Ling/wk10/1-mon/express/package.json, 12-Joshua-Ling/wk10/1-mon/express/views/form.ejs, 12-Joshua-Ling/wk10/1-mon/express/views/result.ejs, 12-Joshua-Ling/wk10/1-mon/pokemon/index.js, 12-Joshua-Ling/wk10/1-mon/pokemon/package-lock.json, 12-Joshua-Ling/wk10/1-mon/pokemon/package.json, 12-Joshua-Ling/wk10/1-mon/pokemon/views/home.ejs, 12-Joshua-Ling/wk10/1-mon/pokemon/views/pokemon.ejs
=> pokemon api and stocks api

13-Karen-Liang/wk10/1-mon/express-stock/index.js, 13-Karen-Liang/wk10/1-mon/express-stock/package-lock.json, 13-Karen-Liang/wk10/1-mon/express-stock/package.json, 13-Karen-Liang/wk10/1-mon/express-stock/views/home.ejs, 13-Karen-Liang/wk10/1-mon/express-stock/views/result.ejs, 13-Karen-Liang/wk10/1-mon/recipe/index.js, 13-Karen-Liang/wk10/1-mon/recipe/package-lock.json, 13-Karen-Liang/wk10/1-mon/recipe/package.json, 13-Karen-Liang/wk10/1-mon/recipe/views/food.ejs, 13-Karen-Liang/wk10/1-mon/recipe/views/home.ejs
=> complete mon wk10

02-Akiko-Yamasaki/wk10/1-mon/nodehw/index.js, 02-Akiko-Yamasaki/wk10/1-mon/nodehw/package-lock.json, 02-Akiko-Yamasaki/wk10/1-mon/nodehw/package.json, 02-Akiko-Yamasaki/wk10/1-mon/nodehw/views/answer.ejs, 02-Akiko-Yamasaki/wk10/1-mon/nodehw/views/home.ejs
There is a bug, and i don't get stock price. I  attempted a few different way, but can not find what I did wrong. gussing it is a major mistake i have made without realising it
- How difficult did you find this (out of 10)? (0 being no problems at all, 10 being impossible) 
- 2hr
=> node homework

14-Kee-Ming-Brandon/wk10/1-mon/stock-lookup/index.js, 14-Kee-Ming-Brandon/wk10/1-mon/stock-lookup/package-lock.json, 14-Kee-Ming-Brandon/wk10/1-mon/stock-lookup/package.json, 14-Kee-Ming-Brandon/wk10/1-mon/stock-lookup/views/home.ejs, 14-Kee-Ming-Brandon/wk10/1-mon/stock-lookup/views/stockprice.ejs
=> COMPLETE wk10 1-mon HW Stock lookup

21-Tristan-Bartolome/wk10/1-mon/stock-checker/index.js, 21-Tristan-Bartolome/wk10/1-mon/stock-checker/package-lock.json, 21-Tristan-Bartolome/wk10/1-mon/stock-checker/package.json, 21-Tristan-Bartolome/wk10/1-mon/stock-checker/views/home.ejs, 21-Tristan-Bartolome/wk10/1-mon/stock-checker/views/result.ejs
=> stock-checker complete

06-Eugene-Teo/wk10/1-mon/stocksearch/index.js, 06-Eugene-Teo/wk10/1-mon/stocksearch/package-lock.json, 06-Eugene-Teo/wk10/1-mon/stocksearch/package.json, 06-Eugene-Teo/wk10/1-mon/stocksearch/views/home.ejs, 06-Eugene-Teo/wk10/1-mon/stocksearch/views/info.ejs
=> stocksearch w external API

16-Ramez-Al-Siddiq/wk10/3-wed/linked-lists/.gitignore, 16-Ramez-Al-Siddiq/wk10/3-wed/linked-lists/LinkedList.js, 16-Ramez-Al-Siddiq/wk10/3-wed/linked-lists/package-lock.json, 16-Ramez-Al-Siddiq/wk10/3-wed/linked-lists/package.json, 16-Ramez-Al-Siddiq/wk10/3-wed/linked-lists/readme.md, 16-Ramez-Al-Siddiq/wk10/3-wed/linked-lists/test/index.js
- How difficult did you find this (out of 10)? (0 being no problems at all, 10 being impossible) - 9
- Roughly how long did it take? - 2.5 hours
=> COMPLETE - got some tests working - 24/05/2023

15-Maggie-Cameron/wk10/3-wed/linked-lists/.gitignore, 15-Maggie-Cameron/wk10/3-wed/linked-lists/LinkedList.js, 15-Maggie-Cameron/wk10/3-wed/linked-lists/package-lock.json, 15-Maggie-Cameron/wk10/3-wed/linked-lists/package.json, 15-Maggie-Cameron/wk10/3-wed/linked-lists/readme.md, 15-Maggie-Cameron/wk10/3-wed/linked-lists/singly-linked-list.rb, 15-Maggie-Cameron/wk10/3-wed/linked-lists/test/index.js
- 9. the only reason it is not 10 is because i presume i could have found a tutorial if i had infinite time 
=> 3 passing tests only

02-Akiko-Yamasaki/wk10/3-wed/linked-lists/.gitignore, 02-Akiko-Yamasaki/wk10/3-wed/linked-lists/LinkedList.js, 02-Akiko-Yamasaki/wk10/3-wed/linked-lists/package-lock.json, 02-Akiko-Yamasaki/wk10/3-wed/linked-lists/package.json, 02-Akiko-Yamasaki/wk10/3-wed/linked-lists/readme.md, 02-Akiko-Yamasaki/wk10/3-wed/linked-lists/singly_linked_list.rb, 02-Akiko-Yamasaki/wk10/3-wed/linked-lists/test/index.js
not quite understand it but attempted some
=> linked list hw

12-Joshua-Ling/wk10/4-thu/singly_linked_list.rb
=> singly linked list

06-Eugene-Teo/wk10/4-thu/linked-lists/.gitignore, 06-Eugene-Teo/wk10/4-thu/linked-lists/LinkedList.js, 06-Eugene-Teo/wk10/4-thu/linked-lists/package-lock.json, 06-Eugene-Teo/wk10/4-thu/linked-lists/package.json, 06-Eugene-Teo/wk10/4-thu/linked-lists/readme.md, 06-Eugene-Teo/wk10/4-thu/linked-lists/test/index.js
7? Had to draw out on paper the head and nodes to really visualise, still took a long while to wrap my head around the concepts
=> partially completed linkedlist

15-Maggie-Cameron/wk01/5-fri/mta_lab/js/exercises.js
As you know I REALLY struggled with this at the time it was set. I cannot get my head around how people could have got it working at the end of week 1. It's been bugging me all course that I wasn't able to do it. Anyway I gave it another go over the weekend and it was so satisfying to easily complete it.
- 10 weeks lol
=> finally finished MTA lol

01-Adam-Shuvalov/wk10/4-thu/singly-linked-list.rb
Bit tough, done most of the methods
=> Done most of the linked list methods
